version: '3'

services:
  
  payment-backend:
    image: vivaconagua/payment-backend:latest
    build: .
    restart: unless-stopped
    env_file:
        - .env
    networks:
      api_net:

networks:
  api_net:
    external:
        name: api_net
