version: '3'

services:
  
  app:
    build: .
    restart: unless-stopped
    volumes:
        - ${REPO_CONFIG_PATH}/payment-backend/prod.env:/go/src/payment-backend/.env
    environment:
        - ALLOW_ORIGINS=${ALLOW_ORIGINS}
        - COOKIE_SECURE=${COOKIE_SECURE}
        - SAME_SITE=${SAME_SITE}
    networks:
      app_net:
          aliases:
              - payment-backend
networks:
  app_net:
    external:
        name: api-deploy_app
