version: '3'

services:
  
  app:
    build: .
    restart: unless-stopped
    volumes:
        - ${REPO_CONFIG_PATH}/payment-backend/prod.env:/go/src/payment-backend/.env
    environment:
        - ALLOW_ORIGINS=${ALLOW_ORIGINS}
        - COOKIE_SECURE=${COOKIE_SECURE}
        - SAME_SITE=${SAME_SITE}
    networks:
      app_net:
          aliases:
              - payment-backend
  db:
    image: mongo
    env_file: 
      - ${REPO_CONFIG_PATH}/payment-backend/prod.env
    restart: unless-stopped
    volumes: 
      - ${VOLUME_PATH}/payment-backend/mongo/:/etc/mongo
          #- ./config/drops-backend/drops-init.js:/docker-entrypoint-initdb.d/drops-init.js:ro  
    networks:
      db_net:

networks:
  app_net:
    external:
        name: api-deploy_app
  
  db_net:
    external:
        name: api-deploy_db
